import './globals.css';
import type { Metadata } from 'next';
import Nav from '@/components/Nav/Nav';

export const metadata: Metadata = {
  title: 'Compileit Case',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex relative">
        <Nav />
        {children}
      </body>
    </html>
  );
}
